FROM openjdk:11

MAINTAINER zms<1974525360.qq.com>

WORKDIR /app

ADD kee-model-rocketmq-producer.jar /app/kee-model-rocketmq-producer.jar

VOLUME /app/logs

EXPOSE 9211

ENTRYPOINT ["java","-jar","kee-model-xxx.jar"]