FROM openjdk:11

MAINTAINER zms<1974525360.qq.com>

WORKDIR /app

ADD kee-model-rocketmq-consumer.jar /app/kee-model-rocketmq-consumer.jar

VOLUME /app/logs

EXPOSE 9210

ENTRYPOINT ["java","-jar","kee-model-xxx.jar"]